#!/usr/bin/env bash

ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )

TARGET_CONFIGS="$HOME/.config/dotfiles"

BASHRC="$HOME/.bashrc"
BASHPROFILE="$HOME/.bash_profile"

is_mac() {
  local unamestr=`uname`
  test $unamestr == 'Darwin'
}

is_linux() {
  local unamestr=`uname`
  test $unamestr == 'Linux'
}

is_ubuntu() {
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    test "$ID" == "ubuntu"
  else
    return 1
  fi
}

is_centos() {
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    test "$ID" == "amzn" -o "$ID" == "amazon" -o "$ID" == "centos"
  else
    return 1
  fi
}

get_target_folder() {
  local target_dir=$( cd "$( dirname "$0" )" && pwd )
  echo $(dirname "$target_dir")
}

get_target_name() {
  local target_dir=$( cd "$( dirname "$0" )" && pwd )
  echo $(basename "$target_dir")
}

get_target_config() {
  local target=$(get_target_name)
  echo "$TARGET_CONFIGS/$target"
}

get_source() {
  local targets=$(get_target_folder)
  local name=$(get_target_name)
  echo $targets/$name
}

is_sourced() {
   if [ -n "$ZSH_VERSION" ]; then 
       case $ZSH_EVAL_CONTEXT in *:file:*) return 0;; esac
   else  # Add additional POSIX-compatible shell names here, if needed.
       case ${0##*/} in dash|-dash|bash|-bash|ksh|-ksh|sh|-sh) return 0;; esac
   fi
   return 1  # NOT sourced.
}

message() {
  local message="$1"
  local color=${2:-35}
  local target=$(get_target_name)
  echo -e "\033[${color}mDOTFILES($target):\033[0m $message"
}

error() {
  local message=${1:-"Something went wrong"}
  local code=${2:-1}
  local color=31
  message "$message" 31
  return $code
}

log() {
  message "$1" 35
}

assert_prev() {
  local message=${1:-"Something went wrong"}
  local code=${2:-1}
  [[ $? != 0 ]] && error $message $code && sleep 5m
}

tolower() {
  echo $(echo $1 | tr '[:lower:]' '[:upper:]')
}

tolower() {
  echo $(echo $1 | tr '[:upper:]' '[:lower:]')
}

yesno() {
  local display=$1; shift
  local default=$(tolower ${1:-yes}); shift
  while true
  do
    if [[ $default == "yes" ]]; then
      echo "${display} YES/no?"
    else
      echo "${display} yes/NO?"
    fi

    read -r answer
    [[ -z "$answer" ]] && answer=$default

    answer=$(tolower $answer)
    case $answer in
      yes)
        return 0
        ;;
      no)
        return 1
        ;;
      *)
        error "You must choose between \"yes\" or \"no\""
        ;;
    esac
  done
}

bash_newline() {
  local target_config=$(get_target_config)
  echo $1 >> $target_config
}

bash_section() {
  bash_newline
  bash_newline "# $1"
}

# Creates a target specific bash file, e.g. in ~/.config/dotfiles/<TARGET>.
# <TARGET> is the name of the directory containing the executing bash script.
# This file is then sources from ~/.bashrc. If the target file already exists,
# it is cleared and it is assumed it is already sources from ~/.bashrc
bash_init_config() {
  if [ ! -d "$TARGET_CONFIGS" ]; then
    log "Create '$TARGET_CONFIGS'"
    mkdir -p $TARGET_CONFIGS
  fi

  local target_config=$(get_target_config)
  if [ ! -f "$target_config" ]; then
    log "Sourcing '$TARGET_CONFIGS' from $BASHRC"
    echo "source $target_config" >> $BASHRC
  fi

  log "Initialising '$target_config'"
  rm -f $target_config >& /dev/null
  bash_newline "#!/usr/bin/env bash"
  bash_newline
  bash_newline "# This file is automatically generated by the installer." 
  bash_newline "# Do NOT change anything here!"
  bash_newline 
  bash_newline "# Do nothing if this shell isn't on the first level"
}

bash_export_path() {
  local target_config=$(get_target_config)
  echo "export PATH=\"$1:\$PATH\"" >> $target_config
}

bash_export_source() {
  local target_config=$(get_target_config)
  echo "source $1" >> $target_config
}

bash_export_source_maybe() {
  local target_config=$(get_target_config)
  echo "if [ -f \"$1\" ]; then" >> $target_config
  echo "  source $1" >> $target_config
  echo "fi" >> $target_config
}

bash_export_global() {
  local target_config=$(get_target_config)
  echo "export $1=$2" >> $target_config
}

# ============================================================================
# Kiro installation helpers
# ============================================================================
# The kiro target and any downstream dotfiles-* extensions share ~/.kiro/ but
# each owns different entries. These helpers support composition: each target
# manages only its own symlinks, leaving entries owned by other targets
# untouched.
#
# Layout:
#   ~/.kiro/skills/<ns>/      -> namespace folder symlink (one per repo)
#   ~/.kiro/steering/<ns>/    -> namespace folder symlink (one per repo)
#   ~/.kiro/agents/<name>     -> per-file symlinks (flat, required by kiro)
#   ~/.kiro/settings/<name>   -> per-file symlinks (flat, required by kiro)
#   ~/.kiro/prompts/<name>    -> per-file symlinks (flat, required by kiro)
#
# Skills and steering use folder-namespace symlinks so content added to a
# source repo appears immediately without re-linking. Agents, settings,
# and prompts are flat per-file because Kiro expects specific filenames
# at the top level of those dirs (nesting is not supported for those).
#
# All helpers are idempotent. The per-file helper only touches symlinks
# that point into the given source prefix, so re-running one installer
# never disturbs entries owned by another target.

# Ensure a path is a real directory. If it is a symlink (e.g. from the
# legacy whole-directory install), remove the symlink before creating.
kiro_ensure_real_dir() {
  local dir=$1
  if [ -L "$dir" ]; then
    log "Replacing legacy symlink with real dir: $dir"
    rm -f "$dir"
  fi
  mkdir -p "$dir"
}

# Remove symlinks in $dest that point into $src_prefix. Leaves real files
# and symlinks owned by other targets untouched.
kiro_prune_owned_symlinks() {
  local dest=$1 src_prefix=$2
  [ -d "$dest" ] || return 0
  shopt -s nullglob
  local entry target
  for entry in "$dest"/*; do
    if [ -L "$entry" ]; then
      target=$(readlink "$entry")
      if [[ "$target" == "$src_prefix"* ]]; then
        rm -f "$entry"
      fi
    fi
  done
  shopt -u nullglob
}

# Namespace link: $dest/$namespace -> $src (whole directory).
# Used for skills and steering so both repos can publish entries without
# colliding, and new content appears without re-linking.
kiro_link_namespace() {
  local dest=$1 namespace=$2 src=$3
  kiro_ensure_real_dir "$dest"
  local link="$dest/$namespace"
  if [ -e "$link" ] && [ ! -L "$link" ]; then
    error "$link exists and is not a symlink — refusing to overwrite"
    return 1
  fi
  ln -sfn "$src" "$link"
}

# Link every file at the top level of $src into $dest as flat symlinks.
# Skips hidden files (.DS_Store etc). Prunes stale symlinks owned by this
# source before relinking so deletions in the source are reflected.
kiro_link_files_flat() {
  local dest=$1 src=$2
  kiro_ensure_real_dir "$dest"
  kiro_prune_owned_symlinks "$dest" "$src"
  local f name target
  shopt -s nullglob
  for f in "$src"/*; do
    [ -f "$f" ] || continue
    name=$(basename "$f")
    [[ "$name" == .* ]] && continue
    target="$dest/$name"
    if [ -e "$target" ] && [ ! -L "$target" ]; then
      log "SKIP $dest/$name (real file exists)"
      continue
    fi
    ln -sfn "$f" "$target"
  done
  shopt -u nullglob
}
