export PATH=$HOME/bin:/usr/local/bin:/opt/local/bin:$PATH
export EDITOR=vim

if command -v brew > /dev/null
then
    completion="$(brew --prefix)/etc/bash_completion"
    if [[ -f $completion ]]
    then
        source $completion
    fi
fi

palette="$HOME/.vim/bundle/gruvbox/gruvbox_256palette_osx.sh"
if [[ -f $palette ]]
then
    source $palette
fi

# if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
#     GIT_PROMPT_THEME=Solarized
#     source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
#     GIT_PROMPT_END=
# fi

# Common
alias sudo='sudo '
alias ls='ls -G --color'
alias ll='ls -lah --color'
alias ggl='git log --graph --all --pretty --abbrev-commit --decorate'

# Ranger
export RANGER_LOAD_DEFAULT_RC=FALSE
alias ra='ranger'
